### PR TITLE
Fix CMP0042 Mac OS X

### PR DESCRIPTION
**Pull request by armm77**
Set a consistent MACOSX_RPATH default across all CMake versions.
When CMake 2.8.12 is required, change this default to 1.
When CMake 3.0.0 is required, remove this block (see CMP0042).
ref: http://www.cmake.org/cmake/help/v3.0/policy/CMP0042.html

### CODE REVIEW

**Comment by sanctum32** [comment]
We could use CMAKE_MAJOR_VERSION cmake variable for it too
it would look:
if (CMAKE_MAJOR_VERSION GREATER 3 OR CMAKE_MAJOR_VERSION EQUAL 3)
   IF ( NOT DEFINED CMAKE_MACOSX_RPATH )
       SET( CMAKE_MACOSX_RPATH 0)
   ENDIF()
else()
   IF ( NOT DEFINED CMAKE_MACOSX_RPATH )
       SET( CMAKE_MACOSX_RPATH 1)
   ENDIF()
endif()

I'm not going to up cmake requirements currently because most of unix systems (bsd and linux) uses older versions by default in their cloud repositories (mostly cmake 2.8 version)

**Comment by sanctum32** [comment]
Anyway i still need to inspect that policy...

**Comment by armm77** [comment]
Your proposal is better.

**Comment by sanctum32** [comment]
Thanks for this, I'll push it in few minutes with your authority ;) 
Anyway I need to do build and run tests on OS X because basically its unknown how core actually compiles/works and how well uses hardware on that system. On windows build small part of usage is increased by outdated dependencies which contains some possible performance issues.

**Comment by sanctum32** [comment]
https://github.com/EasyWoW/wotlk-core/commit/36834ec19281cd209457f0a3b6bf4b8cf10c610e Decided to enable it directly. I raised requirement a little to keep it working right.

**Pull request closed without merging**
