### PR TITLE
Battlegrounds/WarsongGulch: Fix small to position to player on map. And missing data.

### PR DESCRIPTION
**Pull request by armm77**

### CODE REVIEW

**Comment by sanctum32** [comment]
I'm going to take objects from trinitycore because there is a lot of them still missing here.
in wsgObjectLocation i'm going to remove map entry and replace direct definition usage in spawnBgObject. About alliance and horde lines missmatch, well, its my big misstake, i missmatched values a bit for that.
Anyway I'm taking second your commit - it looks very good.

**Comment by sanctum32** [comment]
Thanks for your contribution ;)

**Comment by armm77** [comment]
Ok, very nice. :+1:

**Comment by sanctum32** [comment]
@armm77, i want to note that I'm not going to touch dependencies source because they all needs upragde, its 10 years old dependencies :8ball:

**Comment by armm77** [comment]
ok sorry forget to close this.

**Comment by sanctum32** [comment]
dont worry, atleast you try to contribute, i appreciate it ;) btw i merge your logs changes to core atm manually ;)

**Comment by sanctum32** [comment]
Just try to make patches one by one, its much simpler to catch changes ;)

**Comment by armm77** [comment]
ok, thanks for your suggestion.

**Comment by sanctum32** [comment]
I did merge of some of your commits but i didn't took dependencies changes only ;) thanks for it again ;)

**Pull request closed without merging**
